[options]

admin_passwd = RovshanBagiyev123!

db_host = db
db_port = 5432
db_user = odoo
db_password = ac6zUt1jVfppRwvWnK33

addons_path = /opt/odoo/odoo/addons,/odoo_models

proxy_mode = True

log_level = info