[options]

admin_passwd = arter123!

db_host = db
db_port = 5432
db_user = odoo
db_password = d8qUtaT5G5thesTedlC9

addons_path = /opt/odoo/odoo/addons,/odoo_models

proxy_mode = True
dbfilter = ^coffee-zone$

log_level = info